spring.application.name=JwtProjectWithVsCode

file.upload-dir=uploads/images
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT}

app.jwt.secret=8a9e7ed8ff67cf383334b0507feeba71f783ef176a84a5dfc1bb6d3edcf892369615661bc163ee0610d616a59bc5c82e30786b7dbd5f2551d2c95c809b26c807
